INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Andreea Summers', 'Odessa', '18')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Alima Matthams', 'Odessa', '25')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Rohaan Cortes', 'Odessa', '29')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Kenya Dodson', 'Odessa', '29')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Wasim Whittle', 'Odessa', '26')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Jamie-Leigh Khan', 'Odessa', '37')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Aoife Mccarty', 'Odessa', '50')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Kira Lucas', 'Odessa', '50')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Roger Avery', 'Odessa', '43')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Kylo Bullock', 'Odessa', '35')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Mackenzie Hubbard', 'Odessa', '35')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Eduardo Watson', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Hibba Lowe', 'Odessa', '23')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Axl Valenzuela', 'Odessa', '26')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Leon Anderson', 'Odessa', '27')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Alexander Mckeown', 'Odessa', '62')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Riley Wong', 'Odessa', '65')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Yusha Alexander', 'Odessa', '30')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Noah Gilliam', 'Odessa', '30')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Jorja Leech', 'Odessa', '33')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Ronny Whiteley', 'Odessa', '44')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Marco Jensen', 'Odessa', '32')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Shaquille Reader', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Trixie Solis', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Sanna Boyle', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Salim Wainwright', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Tyrese Sherman', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Nada Salter', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Anastazja Floyd', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Bo Jones', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Kaylee Andrade', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Kaan Golden', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Neive Garza', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Shyam Harris', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Nelson Gay', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Wiktoria Yu', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Aliesha Wilkinson', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Leonidas Brooks', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Ammarah Haley', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Elvis Goodman', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Taiba Croft', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Abiha Hodge', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Viktoria Lam', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Keisha Arellano', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Lenny Denton', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Hadassah Hendrix', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Patrick Parks', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Rima Lawrence', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Karina Whyte', 'Odessa', '31')
INSERT INTO clients (Client_Name, Client_Adress, Client_Age) VALUES ('Alastair Spears', 'Odessa', '31')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '1')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '2')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '3')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '4')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '5')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '6')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '7')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '8')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '9')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '10')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '11')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '12')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '13')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '14')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '15')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '16')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '17')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '18')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '19')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '20')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '21')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '22')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '23')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '24')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '25')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '26')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '27')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '28')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '29')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '30')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '31')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '32')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '33')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '34')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '35')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '36')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '37')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '38')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '39')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '40')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '41')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '42')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '43')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '44')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '45')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '46')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '47')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '48')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '49')
INSERT INTO accounts (balance, client_id) VALUES ('5000', '50')
